### ISSUE TITLE
FINALLY

### ISSUE THREAD

**Issue by kobykk** [burnedpopcorn/CheesedUP-Web-Port#1]
good job on finally making it but i already got pizza tower and i didnt have the space for cheesed up so yea

**Comment by burnedpopcorn** [comment]
that's fine, I was honestly still gonna do it because I liked the mod and the features
> But I also dont care about the drama about it, I just like the mod

**Comment by burnedpopcorn** [comment]
this is funny

he went out of his way to HARDCODE a ban list
![lol](https://github.com/burnedpopcorn/CheesedUP-Web-Build/assets/164114576/e65c8152-0639-449f-a17b-6381c3156852)
