### ISSUE TITLE
this is not a issue 

### ISSUE THREAD

**Issue by yesderiribrb** [burnedpopcorn/CheesedUP-Web-Port#10]
can I make a video on this and it's just gameplay

**Comment by burnedpopcorn** [comment]
Yeah of course

**Comment by burnedpopcorn** [comment]
I don't care what you choose to do with this port
Hell, I'm not really supposed to even make this port, so I definitely don't have any legal power, and either way, idc

**Comment by yesderiribrb** [comment]
yipeee
