### ISSUE TITLE
This is a very good Wed

### ISSUE THREAD

**Issue by AppleDoise** [burnedpopcorn/CheesedUP-Web-Port#12]
But we need a lot of noise and update. So can we transplant 4.5 or B1.3.1?

**Comment by burnedpopcorn** [comment]
Different ports have to be made separately, and although you can transplant some LINES code, you can't transplant entire scripts over, because of version differences (incompatiblies) and the obvious reason of it wouldn't really be a b1.3.1 port anymore

**Comment by burnedpopcorn** [comment]
Also, I've tried a b1.3.1 port, and even after transplanting some code, it would take way too much work and time, especially because I am currently working on fixing sound on the main port, which will already take a lot of my time

**Comment by AppleDoise** [comment]
> 另外，我尝试了 b1.3.1 端口，即使移植了一些代码，也需要太多的工作和时间才能进入游戏，特别是因为我目前正在修复主端口上的声音，这已经占用了我很多时间

**Comment by AppleDoise** [comment]
Will you know anything new in the future

**Comment by burnedpopcorn** [comment]
Other than updating my current ports, I'm not sure if I what I'll do next, as there's not much source code available, and I'm not good enough to make a game myself

**Comment by burnedpopcorn** [comment]
Also, why is your reply in Chinese?

**Comment by AppleDoise** [comment]
> 除了更新我当前的端口之外，我不确定我下一步该做什么，因为没有太多可用的源代码，而且我自己还不够好，不能制作游戏

**Comment by AppleDoise** [comment]
Because I am. Chinese. Please do not create stereotypes and discrimination

**Comment by burnedpopcorn** [comment]
Oh alright

By the way I was just curious about it

**Comment by AppleDoise** [comment]
> 哦，好吧
> 
> 顺便说一句，我只是好奇

**Comment by AppleDoise** [comment]
I have a problem
![Screenshot_20240720_125637_cyou joiplay joiplay](https://github.com/user-attachments/assets/3840e840-8a90-4991-82fa-579bd26c8d41)
This piece of clothing.The ShadowWhy did it becomeOrange
![Uploading Screenshot_20240720_125610_cyou.joiplay.joiplay.jpg…]()

**Comment by burnedpopcorn** [comment]
That just looks like normal noise

**Comment by AppleDoise** [comment]
😢

**Comment by AppleDoise** [comment]
😢
![Uploading Screenshot_20240720_125610_cyou.joiplay.joiplay.jpg…]()
![Screenshot_20240720_135757_tv danmaku bili_edit_5969365516893295](https://github.com/user-attachments/assets/8b1dfb41-ab4d-4ffb-8275-d423f03529c0)

**Comment by AppleDoise** [comment]
This doesn't look like a real pizza tower💀
![Uploading Screenshot_20240720_125610_cyou.joiplay.joiplay.jpg…]()

**Comment by burnedpopcorn** [comment]
Wait, what version of Pizza Tower are you playing, and are you using my ports

**Comment by AppleDoise** [comment]
> 等一下，你玩的是哪个版本的 Pizza Tower，你是否使用了我的端口？

  I am using your latest one r6
![Uploading Screenshot_20240720_125610_cyou.joiplay.joiplay.jpg…]()

**Comment by AppleDoise** [comment]
I want to play super bo noise

**Comment by burnedpopcorn** [comment]
Then get the mod I guess, but if your on a locked down computer, then you're out of luck

**Comment by AppleDoise** [comment]
Oh, no.  Can you get an lhpp?

**Comment by burnedpopcorn** [comment]
What's a lhpp?

**Comment by AppleDoise** [comment]
> 什么是 lhpp？

**Comment by AppleDoise** [comment]
💀This
![668b2767b8a17](https://github.com/user-attachments/assets/dff015ba-e563-4c67-9bf7-e2f75b165480)

**Comment by AppleDoise** [comment]
When can I add adjustments

**Comment by burnedpopcorn** [comment]
we can continue this conversation here

[![Discord Invite Link](https://theprojects.x10.mx/discord.jpg)](https://discord.gg/BJSkBEPU)
