### ISSUE TITLE
Super Bo Noise Port?

### ISSUE THREAD

**Issue by LOL-183** [burnedpopcorn/CheesedUP-Web-Port#4]
This game is on itch.io, do you plan on making a port of it?

**Comment by burnedpopcorn** [comment]
No, because Cheesed Up already has the character, and I'm just not interested in it myself

**Comment by LOL-183** [comment]
Sugary spire leak build?

**Comment by LOL-183** [comment]
Make port?

**Comment by burnedpopcorn** [comment]
I might do a Sugary Spire port, but very unlikely

**Comment by LOL-183** [comment]
Do you need a link to the game?

**Comment by burnedpopcorn** [comment]
I think I know where to get it, but if you have a specific version you would like me to try and port, then send the link

no promises I do it tho, as always :)

**Comment by burnedpopcorn** [comment]
remember tho, source code is different from a playable windows build, so don't send me a playable build, send me source code

**Comment by LOL-183** [comment]
I not have source code

**Comment by LOL-183** [comment]
https://noiselle2580.itch.io/ssu-sugary-spire-united sugary spire united

**Comment by burnedpopcorn** [comment]
That is a compiled build specifically for Windows, not source code

**Comment by burnedpopcorn** [comment]
Can't find any source code anywhere, and I'm not intrested in a bo noise port, so ima close this issue

**Comment by burnedpopcorn** [comment]
@LOL-183, So i did end up making a Sugary Spire Port
its here: https://github.com/burnedpopcorn/Sugary-Spire-Web-Port
but it isn't the version you wanted tho, but it shouldn't matter
