### ISSUE TITLE
the Hud is large

### ISSUE THREAD

**Issue by yesderiribrb** [burnedpopcorn/CheesedUP-Web-Port#5]
every time I get on the game the screen is large

**Comment by burnedpopcorn** [comment]
What device are you on, because enabling fullscreen works for me

**Comment by burnedpopcorn** [comment]
And if your talking about the standard window size when first loading the game, note that that's not fullscreen

**Comment by yesderiribrb** [comment]
I'm on Chromebook

**Comment by burnedpopcorn** [comment]
Well, did you enable Fullscreen in the Options Menu, or are you playing the game as it is?

**Comment by yesderiribrb** [comment]
i enable Fullscreen in the options menu

**Comment by burnedpopcorn** [comment]
Can you send a screenshot of it

**Comment by yesderiribrb** [comment]
![image](https://github.com/burnedpopcorn/CheesedUP-Web-Port/assets/153571716/ccdf86ba-3d7b-4e25-9a23-251e0d41054b)
![Screenshot 2024-07-08 6 44 34 PM](https://github.com/burnedpopcorn/CheesedUP-Web-Port/assets/153571716/ece948fe-caa5-41cd-8350-6282386671c0)
![Screenshot 2024-07-08 6 43 34 PM](https://github.com/burnedpopcorn/CheesedUP-Web-Port/assets/153571716/658ce450-67ce-4fa2-950f-46aad2b08f1e)

**Comment by burnedpopcorn** [comment]
Yeah, I'm working on getting it to load correctly rn, but the code is being a real pain in the ass
I mean, I got it working correctly, but you need to go to settings and manually change it, so that's not gonna be seamless, so I have to force enable an option, but again, really annoying

**Comment by yesderiribrb** [comment]
ok

**Comment by yesderiribrb** [comment]
I mean the Hud is large

**Comment by burnedpopcorn** [comment]
Alright, I believe I have fixed it
I'm just gonna add some Quality of Life Improvements and then I'll upload it

**Comment by yesderiribrb** [comment]
ok

**Comment by burnedpopcorn** [comment]
Fixed: https://github.com/burnedpopcorn/CheesedUP-Web-Port/releases/tag/r5_COLD

Should be applied to the main site in a bit :)
