### ISSUE TITLE
(Question) Scoutdigo port?

### ISSUE THREAD

**Issue by UltraFatBoi** [burnedpopcorn/CheesedUP-Web-Port#7]
Are we gonna get a web port of Scoutdigo next?

**Comment by burnedpopcorn** [comment]
Is it a ```xdelta``` file that you inject with Pizza Oven, or is it a Full Game Mod like Cheesed Up, because if it's a xdelta or something of that nature, no way in hell, but if its a full game mod, then maybe

**Comment by ShyGuyComputer** [comment]
> Is it a `xdelta` file that you inject with Pizza Oven, or is it a Full Game Mod like Cheesed Up, because if it's a xdelta or something of that nature, no way in hell, but if its a full game mod, then maybe

scoutdigo is an eggplant build mod so no fmod the source code is here: https://rentry.co/PT-Leaked-shit

**Comment by burnedpopcorn** [comment]
@UltraFatBoi @ShyGuyComputer 
I got a "working" Scoutdigo v1.2 web build

**Comment by burnedpopcorn** [comment]
Needs HEAVY work to be considered playable tho
(Game Frame is terrible, as always)

**Comment by burnedpopcorn** [comment]
This port has FULL Sound, unlike the other ports :)

**Comment by yesderiribrb** [comment]
yippe :D

**Comment by burnedpopcorn** [comment]
@yesderiribrb @UltraFatBoi @ShyGuyComputer 

IT HAS BEEN DONE!
https://github.com/burnedpopcorn/PT-Scoutdigo-Web-Port

**Comment by burnedpopcorn** [comment]
There's still work to be done (mostly on the Game Frame), but it works
with audio as well :)
