### ISSUE TITLE
it wont start up

### ISSUE THREAD

**Issue by chubbybelly24** [burnedpopcorn/CheesedUP-Web-Port#8]
I have a chromebook
![Screenshot 2024-07-09 8 41 00 PM](https://github.com/burnedpopcorn/CheesedUP-Web-Port/assets/174736283/4b2a832c-5859-48f0-b2b8-1fdf7da46cc9)

**Comment by burnedpopcorn** [comment]
It can take a while for it to start up
(For me, it's about 20 secs on my fastest computer)

**Comment by burnedpopcorn** [comment]
While loading, it stays on a black screen, so it could look like it doesn't load

**Comment by chubbybelly24** [comment]
I also like the ports keep it up

**Comment by burnedpopcorn** [comment]
Thanks, I'm currently working on a Launcher for GX.GAMES, so more people can find it

**Comment by burnedpopcorn** [comment]
A bunch of people also want me to make even more ports of old builds or mods, so I might port them idk

**Comment by chubbybelly24** [comment]
also sorry if I'm asking for much but do you think your able to get the cyop levels working in pt:CU

**Comment by chubbybelly24** [comment]
thank you so much it stayed at 50 mb of memory and the it satrd the game so thank you

**Comment by burnedpopcorn** [comment]
You're welcome

It's just that Pizza Tower is a pretty big game, so you have to wait a bit for it to load

**Comment by burnedpopcorn** [comment]
Honestly, I'm surprised that the game loads as fast as it does

**Comment by chubbybelly24** [comment]
yeah it started running the game very fast when it started and i have steam proton on the Chromebook that im texting you on right now on the steam proton and then it was at 3 fps and then crashed but in the html its like around 30-ish to 60 fps which is very sepraiseing that it was running that good but i also have been trying to make html a file that brings me to the game 
[Screen recording 2024-07-10 8.11.49 AM.webm](https://github.com/burnedpopcorn/CheesedUP-Web-Port/assets/174736283/2cdd7515-37cb-444f-97cb-022ad18d2eda)

**Comment by chubbybelly24** [comment]
I have game maker 2.0 beta through lunix

**Comment by burnedpopcorn** [comment]
Steam is slow because you're running a the game on a Windows compatability layer in a Linux VM in an already weak hardware. So it's a box inside a box inside a already small box

**Comment by burnedpopcorn** [comment]
what html file are you trying to make, and for what purpose?

**Comment by chubbybelly24** [comment]
just to have it as a chromebook app

**Comment by burnedpopcorn** [comment]
I don't know much about how to make it a chromebook app,  but I think I could do something.  Maybe I could steal some code from s3&k web port

**Comment by burnedpopcorn** [comment]
I have a re-upload in my github repos, so the code is available there
(I mentioned that port because its html file allows for installing the website on your computer)

**Comment by burnedpopcorn** [comment]
I don't know what part of the html file allows for it, but it has to be there, because it appears when I use it

**Comment by chubbybelly24** [comment]
how do I import a html of pt CU in gamemaker 2 beta

**Comment by burnedpopcorn** [comment]
One thing you gotta learn

The source code is different from a compiled build (the html file and other files)

And you can't change how Gamemaker compiles the html file, especially because they just reuse the same template, so you would have to manually make changes to the html file itself.

Also there are more files that are necessary for the game to launch, such as some Javascript files, WebAssembly files, and the proprietary .unx file, not just the html file

**Comment by chubbybelly24** [comment]
well I know how to use lunix but I have to use tatorials on how to use it for stuff I want to do

**Comment by burnedpopcorn** [comment]
So, I found some documentation on Github, and I think I can do it myself

I'll update you when I can

**Comment by chubbybelly24** [comment]
ok thanks

**Comment by burnedpopcorn** [comment]
So I tried everything I could find, and nothing

My really only excuse is that the documentation was old and out-of-date, and no one else seemed to know how it works

**Comment by burnedpopcorn** [comment]
I think you might be able to install it just by clicking on the three dot button, and searching for 'Install' or 'Add to Homescreen'

But idk
