### ISSUE TITLE
when you spawn in fake peppino and hit him about 2 or 3 times he dissapears(I was talking about the clones my bad)

### ISSUE THREAD

**Issue by nolan540** [burnedpopcorn/CheesedUP-Web-Port#9]
the title explains but still fake peppino is disappearing and idk why

**Comment by burnedpopcorn** [comment]
I haven't fought fake peppino in this port yet, so I will try it out rn

**Comment by burnedpopcorn** [comment]
I beat the boss and completed the escape sequence, so I don't know what could be causing that

Maybe different characters/mods?

**Comment by nolan540** [comment]
no I'm talking in debug then I closed the issue because I realized what the descritpon for experimental said...lemme explain if you turn on experimental in modded in setting press 1 then enter 10 and click anyway where fake pep will spawn and once you hit him and clones appear the don't exist idk if this is because its not in the boss room but yea

**Comment by nolan540** [comment]
![Screenshot 2024-07-14 2 21 57 AM](https://github.com/user-attachments/assets/5d3a2d48-9956-4e3d-90b1-bd742715a916)

**Comment by nolan540** [comment]
pic of me using debug

**Comment by burnedpopcorn** [comment]
Oh, so you used Experimental settings. Well then it's not really an issue if it's Experimental

**Comment by nolan540** [comment]
understood
